diff --git a/util/archutil/Dockerfile b/util/archutil/Dockerfile
index 2b24b23..89036e6 100644
--- a/util/archutil/Dockerfile
+++ b/util/archutil/Dockerfile
@@ -1,4 +1,4 @@
-FROM debian:bullseye-slim AS base
+FROM debian:trixie-slim AS base
 RUN apt-get update && apt-get --no-install-recommends install -y \
   gcc-x86-64-linux-gnu \
   binutils-arm-linux-gnueabihf \
@@ -8,7 +8,8 @@ RUN apt-get update && apt-get --no-install-recommends install -y \
   binutils-s390x-linux-gnu \
   binutils-powerpc64le-linux-gnu \
   binutils-mips64el-linux-gnuabi64 \
-  binutils-mips64-linux-gnuabi64
+  binutils-mips64-linux-gnuabi64 \
+  binutils-loongarch64-linux-gnu
 WORKDIR /src
 
 
@@ -52,6 +53,10 @@ FROM base AS exit-mips64
 COPY fixtures/exit.mips64.s .
 RUN mips64-linux-gnuabi64-as --noexecstack -o exit.o exit.mips64.s && mips64-linux-gnuabi64-ld -o exit -s exit.o
 
+FROM base AS exit-loong64
+COPY fixtures/exit.loong64.s .
+RUN loongarch64-linux-gnu-as --noexecstack -o exit.o exit.loong64.s && loongarch64-linux-gnu-ld -o exit -s exit.o
+
 FROM golang:1.20-alpine AS generate
 WORKDIR /src
 COPY --from=exit-amd64 /src/exit amd64
@@ -64,9 +69,10 @@ COPY --from=exit-ppc64 /src/exit ppc64
 COPY --from=exit-ppc64le /src/exit ppc64le
 COPY --from=exit-mips64le /src/exit mips64le
 COPY --from=exit-mips64 /src/exit mips64
+COPY --from=exit-loong64 /src/exit loong64
 COPY generate.go .
 
-RUN go run generate.go amd64 386 arm64 arm riscv64 s390x ppc64 ppc64le mips64le mips64 && ls -l
+RUN go run generate.go amd64 386 arm64 arm riscv64 s390x ppc64 ppc64le mips64le mips64 loong64 && ls -l
 
 
 FROM scratch
